CREATE PROCEDURE  [dbo].[LIST_AND_UPDATE_REQUESTS_READY_TO_CANCEL]      
(      
 @LOG_NUMBER int = NULL,
 @LANGUAGE VARCHAR(10) = NULL    
)      
AS      
BEGIN      
 SET NOCOUNT ON  
   
 BEGIN TRANSACTION    
 
 
	 ;WITH CTE_CAT AS (
			SELECT	CALL_CENTER_ID,
					CAT_CODE,
					[DESC]
			FROM dbo.PROBLEM_CATEGORIES
			WHERE [LANGUAGE] = @LANGUAGE
			AND [DESC] <> ''
		), CTE_ITEM_CAT AS (
			SELECT	[ITEM_CAT_CODE],
					[ITEM]
			FROM dbo.PROBLEM_ITEM_CATEGORIES
			WHERE [LANGUAGE] = @LANGUAGE
			AND [ITEM] <> ''
		), CTE_PROBLEM_TYPES AS (
			SELECT	TYPE_CODE,
					[DESC]
			FROM dbo.PROBLEM_TYPES
			WHERE [LANGUAGE] = @LANGUAGE
			AND [DESC] <> ''
		)  
	 SELECT    
		'' AS 'WF_REQ_ID',    
		a.[REQUEST_ID],      
		a.[ITEM_ID],      
		a.[REQUEST_NO],      
		a.[UTC_REQUIRED_DATE],      
		a.[USER_ID],      
		g.[FULL_NAME] AS 'USER_NAME',      
		a.[REQUESTOR_ID],      
		h.[FULL_NAME] AS 'REQUESTOR_NAME',      
		a.[TYPE],      
		a.[DESC],      
		a.[PRIORITY],      
		f.[VALUE] AS 'PRIORITY_DESC',      
		'P' AS 'CURRENT_STATE',      
		'Workflow-Initiated' AS 'CURRENT_STATE_DESC',      
		a.[UTC_START_DATE],      
		a.[UTC_FINISH_DATE],      
		a.[ISTEMPLATE],      
		a.[PARENT_NO],      
		a.[NOTE],      
		a.[JUSTIFICATION],      
		a.[ATTACHMENT],      
		a.[JOB_NO],      
		a.[WORK_LOCATION],      
		a.[REGION_ID],      
		ISNULL(a.[LAST_APPR_SEQ_NO],0) AS 'LAST_APPR_SEQ_NO',      
		a.[LAST_APPR_ID],      
		i.[FULL_NAME] AS 'LAST_APPR_NAME',      
		a.[UTC_LAST_APPR_DATE],      
		a.[LAST_HANDLER_ID],      
		m.[FULL_NAME] AS 'LAST_HANDLER_NAME',    
		a.[UTC_LAST_HANDLING_DATE],      
		a.[CREATED_BY],      
		a.[UTC_CREATED_DATE],      
		a.[UPDATED_BY],      
		a.[UTC_UPDATED_DATE],      
		a.[UTC_LAST_REOPEN_DATE],      
		c.[ITEM_CAT_CODE],      
		--c.[ITEM] AS 'ITEM_DESC',
		ISNULL(CTE_ITEM_CAT.[ITEM], c.[ITEM]) AS 'ITEM_DESC',      
		d.[CAT_CODE],      
		--d.[DESC] AS 'CAT_CODE_DESC',
		ISNULL(CTE_CAT.[DESC], d.[DESC]) AS 'CAT_CODE_DESC',      
		e.[TYPE_CODE],      
		--e.[DESC] AS 'TYPE_CODE_DESC',
		ISNULL(CTE_PROBLEM_TYPES.[DESC], e.[DESC]) AS 'TYPE_CODE_DESC',       
		b.[CALL_CENTER_ID],      
		cc.[DESC] AS 'CALL_CENTER_NAME',    
		b.[APPROVAL_FLOW_ID],      
		b.[REQ_FLOW_ID],    
		a.[LAST_WORKGROUP_CODE] AS 'WORKGROUP_CODE',    
		ISNULL(p.[DESC], '') AS 'WORKGROUP_NAME',    
		a.[LAST_RESOLUTION_COMMENT] AS 'RESOLUTION_DESC',    
		ISNULL(b.[EXTENDED_TYPE],'') AS 'EXTENDED_TYPE',      
		ISNULL(j.[EXTENDED_VALUE_1],'') AS 'EXTENDED_VALUE_1',      
		ISNULL(j.[EXTENDED_VALUE_2],'') AS 'EXTENDED_VALUE_2',      
		ISNULL(j.[EXTENDED_VALUE_3],'') AS 'EXTENDED_VALUE_3',      
		ISNULL(j.[EXTENDED_VALUE_4],'') AS 'EXTENDED_VALUE_4',      
		ISNULL(j.[EXTENDED_VALUE_5],'') AS 'EXTENDED_VALUE_5',      
		ISNULL(j.[EXTENDED_VALUE_6],'') AS 'EXTENDED_VALUE_6',      
		ISNULL(k.[CM_TYPE],'') AS 'CM_TYPE',    
		ISNULL(k.[RISK_LEVEL],'') AS 'RISK_LEVEL',    
		k.[ISDOWNTIME_REQUIRED], 
		ISNULL(k.[DOWNTIME_DURATION_MM],0) AS 'DOWNTIME_DURATION_MM',    
		ISNULL(k.[SERVER_AFFECTED],'') AS 'SERVER_AFFECTED',    
		k.[ISTESPLAN_SUBMITTED],    
		k.[ISNEED_ANNOUNCEMENT],    
		ISNULL(k.[TIMEZONE],'') AS 'TIMEZONE',    
		k.[WORKGROUP_CODE] AS 'CM_WORKGROUP_CODE',    
		ISNULL(o.[DESC], '') AS 'CM_WORKGROUP_NAME',    
		k.[HANDLER_ID],    
		s.[FULL_NAME] AS 'HANDLER_NAME',    
		k.[CM_START_DATE],    
		k.[CM_FINISH_DATE],    
		ISNULL(k.[RESOURCES_AFFECTED],'') AS 'RESOURCES_AFFECTED',    
		ISNULL(k.[BACKOUT_PLAN],'') AS 'BACKOUT_PLAN',    
		k.[ISSUCCESSFUL],    
		k.[ACTUAL_CM_START_DATE],    
		k.[ACTUAL_CM_FINISH_DATE],    
		ISNULL(k.[ACTUAL_DOWNTIME_DURATION_MM],0) AS 'ACTUAL_DOWNTIME_DURATION_MM',    
		ISNULL(k.[COMMENTS],'') AS 'COMMENTS',    
		ISNULL(k.[UPDATE_COUNT],0) AS 'UPDATE_COUNT',    
		k.[ISGLOBAL],    
		l.[REQUEST_NO] AS 'PARENT_REQUEST_NO',      
		l.[ISTEMPLATE] AS 'PARENT_ISTEMPLATE',    
		l.[ITEM_ID] AS 'PARENT_ITEM_ID',    
		l.[CURRENT_STATE] AS 'PARENT_REQUEST_CURRENT_STATE',    
		l.[UTC_CREATED_DATE] AS 'PARENT_REQUEST_UTC_CREATED_DATE',    
		CASE WHEN pr.PARENT_NO IS NOT NULL THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END AS 'ISPARENT',    
		ISNULL(n2.[VALUE],ISNULL(n.[VALUE], '')) AS 'HD_LOCATION',    
		ISNULL(a.[ISHIDE_TO_REQUESTOR],0) AS 'ISHIDE_TO_REQUESTOR',     
		ISNULL(b.[ISHIDE_TO_REQUESTOR],0) AS 'ISHIDE_TO_REQUESTOR_GENERAL',    
		ISNULL(b.[WORKGROUP_OWNER],'') AS 'WORKGROUP_OWNER',  
		ISNULL(b2.[WORKGROUP_OWNER],'') AS 'WORKGROUP_OWNER_PARENT',  
		CAST(l.[WF_REQ_ID] AS VARCHAR(36)) AS 'PARENT_WF_REQ_ID',    
		a.[LAST_COMMENT] AS 'ASSIGNEE_COMMENT'
	   FROM [dbo].[REQUESTS] AS a WITH (UPDLOCK, READPAST)    
	   INNER JOIN [dbo].[PROBLEM_ITEMS] AS b  ON a.[ITEM_ID] = b.[ITEM_ID]      
	   LEFT OUTER JOIN [dbo].[EXTENDED_INFO] AS j  ON a.[REQUEST_ID] = j.[REQUEST_ID] AND b.[CALL_CENTER_ID] = j.[CALL_CENTER_ID] AND b.[EXTENDED_TYPE] = j.[EXTENDED_TYPE]      
	   LEFT OUTER JOIN [dbo].[CHANGE_MANAGEMENTS] AS k  ON a.[REQUEST_ID] = k.[REQUEST_ID]      
	   INNER JOIN [dbo].[PROBLEM_ITEM_CATEGORIES] AS c  ON b.[ITEM_CAT_CODE] = c.[ITEM_CAT_CODE] AND c.[LANGUAGE] = 'en'
	   LEFT JOIN CTE_ITEM_CAT ON c.ITEM_CAT_CODE = CTE_ITEM_CAT.ITEM_CAT_CODE
	   INNER JOIN [dbo].[PROBLEM_CATEGORIES] AS d  ON c.[CALL_CENTER_ID] = d.[CALL_CENTER_ID] AND c.[CAT_CODE] = d.[CAT_CODE] AND d.[LANGUAGE] = 'en'      
	   LEFT JOIN CTE_CAT ON d.CALL_CENTER_ID = CTE_CAT.CALL_CENTER_ID AND d.CAT_CODE = CTE_CAT.CAT_CODE
	   INNER JOIN [dbo].[CALL_CENTERS] AS cc  ON cc.[CALL_CENTER_ID] = d.[CALL_CENTER_ID]     
	   INNER JOIN [dbo].[PROBLEM_TYPES] AS e  ON b.[TYPE_CODE] = e.[TYPE_CODE] AND e.[LANGUAGE] = 'en'      
	   LEFT JOIN CTE_PROBLEM_TYPES ON e.TYPE_CODE = CTE_PROBLEM_TYPES.TYPE_CODE        
	   INNER JOIN [dbo].[LOOKUPS] AS f  ON f.[CALL_CENTER_ID] = cc.[CALL_CENTER_ID] AND f.[TYPE] = 'REQUEST.PRIORITY' AND f.[CODE] = a.[PRIORITY]       
	   LEFT OUTER JOIN [dbo].[REQUESTS] AS l  ON l.[REQUEST_ID] = a.[PARENT_NO]    
	   LEFT OUTER JOIN [dbo].[PROBLEM_ITEMS] AS b2  ON b2.[ITEM_ID] = l.[ITEM_ID]      
	   LEFT OUTER JOIN [dbo].[LOOKUPS] AS n  ON n.[CALL_CENTER_ID] = cc.[CALL_CENTER_ID] AND n.[TYPE] = 'GER_LOCATION_HELPDESK_MAPPING'  AND n.[CODE] = a.[REGION_ID]    
	   LEFT OUTER JOIN [dbo].[LOOKUPS] AS n2  ON n2.[CALL_CENTER_ID] = cc.[CALL_CENTER_ID] AND n2.[TYPE] = 'GER_LOCATION_HELPDESK_MAPPING_EXCEPTION'  AND n2.[CODE] = a.[WORK_LOCATION]    
	   LEFT OUTER JOIN [dbo].[WORKGROUPS] AS o  ON o.[CALL_CENTER_ID] = cc.[CALL_CENTER_ID] AND o.[WORKGROUP_CODE] = k.[WORKGROUP_CODE]      
	   LEFT OUTER JOIN [dbo].[WORKGROUPS] AS p  ON p.[CALL_CENTER_ID] = cc.[CALL_CENTER_ID] AND p.[WORKGROUP_CODE] = a.[LAST_WORKGROUP_CODE]      
	   LEFT OUTER JOIN [dbo].[LOOKUPS] AS q  ON q.[CALL_CENTER_ID] = cc.[CALL_CENTER_ID] AND q.[TYPE] = 'SYSTEM.CONFIG' AND q.[CODE] = 'MAX_WORKFLOW_PROCESS_COUNT'
	   LEFT OUTER JOIN [dbo].[VW_GCC_EMPLOYEE_DATA] AS g  ON g.[EMPLOYEE_ID] = a.[USER_ID]    
	   LEFT OUTER JOIN [dbo].[VW_GCC_EMPLOYEE_DATA] AS h  ON h.[EMPLOYEE_ID] = a.[REQUESTOR_ID]
	   LEFT OUTER JOIN [dbo].[VW_GCC_EMPLOYEE_DATA] AS i  ON i.[EMPLOYEE_ID] = a.[LAST_APPR_ID]
	   LEFT OUTER JOIN [dbo].[VW_GCC_EMPLOYEE_DATA] AS m  ON m.[EMPLOYEE_ID] = a.[LAST_HANDLER_ID]
	   LEFT OUTER JOIN [dbo].[VW_GCC_EMPLOYEE_DATA] AS s  ON s.[EMPLOYEE_ID] = k.[HANDLER_ID]
	   LEFT OUTER JOIN [REQUESTS] AS pr  ON pr.[PARENT_NO] = a.[REQUEST_ID]
	   WHERE a.[CURRENT_STATE] IN ('Y','E','P') 
	   AND (
		 DATEDIFF(DAY,a.[UTC_CREATED_DATE],GETUTCDATE()) >= 7 
		 OR 
		 ISNULL(a.[WORKFLOW_PROCESS_COUNT],0) > CAST(RTRIM(LTRIM(ISNULL(q.[VALUE],'0'))) AS INT)
		)   
        
 IF @@ERROR > 0    
  BEGIN  
   ROLLBACK TRANSACTION    
  END  
 ELSE    
  BEGIN  
   COMMIT TRANSACTION    
  END  
  
    SET NOCOUNT OFF  
END