CREATE PROCEDURE [dbo].[UPDATE_REQUEST_STATUS]
	@LOG_NUMBER int, 
	@REQUEST_ID uniqueidentifier,
	@REQUEST_STATUS varchar(25)
AS

	SET NOCOUNT ON
	SET XACT_ABORT ON

	DECLARE @REQUEST_NO int
	
	SELECT @REQUEST_NO = REQUEST_NO 
    FROM dbo.[REQUESTS] (NOLOCK)  
	WHERE REQUEST_ID = @REQUEST_ID
	
    BEGIN TRAN

	UPDATE dbo.[REQUESTS] 
	SET REQUEST_STATUS = @REQUEST_STATUS
	WHERE REQUEST_ID = @REQUEST_ID

	UPDATE dbo.[WORKFLOW_REQUESTS] 
	SET REQUEST_STATUS = @REQUEST_STATUS
	WHERE REQUEST_NO = @REQUEST_NO

    COMMIT TRAN
	
	SET NOCOUNT OFF
	SET XACT_ABORT OFF